### PR TITLE
Refine ppu determination for point-based data

### PR DESCRIPTION
**Pull request by RohitRathore1**
It resolves issue #9 

- Calculate pairwise distances between observations for point-based data.
- Use the 5th percentile distance to set the ppu, reducing influence from outliers.
- Introduce an upper bound of 500 for ppu to prevent excessive internal grid density.
- Add warnings to guide users on ppu selection based on their data.

This change enhances the model's ability to adapt its internal grid density based on the context and target datasets' spatial resolution.

### CODE REVIEW

**Comment by tom-andersson** [comment]
Thank you @RohitRathore1. I'll review this feature, but the `deepsensor.egg-info/` commits are suboptimal to have in the git history. Rather than the commit/undo commit above, could you try instead deleting both commits and starting again? This might be relevant: https://stackoverflow.com/questions/36168839/how-to-remove-commits-from-a-pull-request

**Comment by tom-andersson** [comment]
Thanks @RohitRathore1 - converted to draft

**Comment by RohitRathore1** [comment]
> Thanks @RohitRathore1 - converted to draft

@tom-andersson are we having tests for `defaults`? I can't find it

**Comment by tom-andersson** [comment]
Good Q @RohitRathore1! We don't yet have unit tests for automatically inferred model hyperparameters. My sense is that it would be tricky to design such tests, and they would not yield much benefit. In future it would be better to raise a warning that hyperparameters were inferred from the data, and that users should understand the limitations of this.

I think we can proceed without testing for now, but feel free to start a `test_defaults.py` if you are keen.

**Comment by RohitRathore1** [comment]
Hi @tom-andersson, I have implemented the following logic but it is failing two existing tests. Please have a look at it and let me know your reviews:

```
# Point-based variable: calculate ppu based on pairwise distances
        coordinates = var[["x1", "x2"]].values if isinstance(var, pd.DataFrame) else var.values
        
        # Ensure the array is 2D. If it's 1D, reshape it.
        if len(coordinates.shape) == 1:
            coordinates = coordinates.reshape(-1, 1)
            
        distances = pdist(coordinates)
        quantile_distance = np.percentile(distances, 5)
        point_ppu = 1 / quantile_distance
        max_ppu = min(max_ppu, point_ppu, 500)  # Introducing an upper bound
        warnings.warn(f"Point-based data detected. ppu set to {max_ppu}. Consider choosing a suitable value based on the data.")
```

The explaination is as following:

- If the data is a DataFrame, it extracts the values of the columns `"x1"` and `"x2"` as coordinates. Otherwise, it assumes the data itself (e.g., a NumPy array) represents the coordinates.
- If the coordinates are 1-dimensional, it reshapes them into a 2D array for compatibility.
- It computes pairwise distances between all the points using the pdist function.
- It calculates the 5th percentile distance from these pairwise distances. This value represents a distance such that 5% of all pairwise distances in the data are below it.
- The reciprocal of this quantile distance is computed to determine the points per unit (ppu) for this data. This indicates how densely the points are packed.
- The ppu is capped at a maximum of 500 for practical reasons.
- A warning is raised to inform the user that point-based data was detected and the computed ppu value is suggested for use.

Short test summary is as following:

```
==================================================================================================== short test summary info ====================================================================================================
FAILED tests/test_model.py::TestModel::test_highlevel_predict_coords_align_with_X_t_offgrid - KeyError: "None of [Index(['x1', 'x2'], dtype='object')] are in the [columns]"
FAILED tests/test_model.py::TestModel::test_model_call_0 - ZeroDivisionError: float division by zero
========================================================================================== 2 failed, 44 passed, 14 warnings in 44.35s ===========================================================================================
```

**Comment by tom-andersson** [comment]
Hi @RohitRathore1, thank you for sharing the code snippet. Find my review below, separated into an overall response about the algorithm, plus some specific comments about the code. I've pushed a commit to this PR which fixes things. Let me know if you have any further suggestions. Otherwise, once you've removed the extraneous commits, I'm happy to merge this PR.

**Overall comment and new commit**
Using the 5% percentile of pairwise distances between all observations is a step in the right direction, but it's not quite the final algorithm we want. Our goal here is to compute some analogue of resolution for non-gridded data. Therefore, we should only care about the *shortest pairwise distances* between observations, not every possible pairwise distance.

Furthermore, pandas data in a `deepsensor.data.TaskLoader` object will be *spatiotemporal* -- its indexes are `time, x1, x2`. Therefore, we can't simply run `pdist` on the entire DataFrame -- we need to be computing distances across space, not time.

I've implemented a simple algorithm that does this in https://github.com/tom-andersson/deepsensor/pull/36/commits/f22ce88c81a9d196f9353de0e022e2b11a08d473 and tests are passing.

**Specific comments on code (if helpful)**
I believe the two tests were failing because:
1) The `pandas` data input and output by `DataProcessor` requires the spatial coordinates as *indexes*, not the columns. Don't worry about missing this - we don't yet have clear documentation for DeepSensor's data requirements.
2) You aren't checking for division by zero in `point_ppu = 1 / quantile_distance`. You can ensure division by zero returns `inf` by using: `np.float64(numerator) / 0.`. However, the division by zero shouldn't be happening in the first place.

Some further comments:
* The check to allow for numpy data at the beginning should be removed. We aren't planning to support numpy data in DeepSensor. IMO it's better to enforce the good practice of using pandas/xarray.
* The check for coordinates being 1D should be removed: a 1D version of DeepSensor is currently not in scope of the project, so we should be assuming 2D spatial coordinates.
* The purpose of the `max_ppu` variable in `deepsensor.model.defaults.gen_ppu` is to track all the inferred data points-per-unit from the context and target sets, and then set the ppu (i.e. model resolution) to be the maximum of these. This wasn't clear and I've improved the handling of this in https://github.com/tom-andersson/deepsensor/pull/36/commits/f22ce88c81a9d196f9353de0e022e2b11a08d473.

**Comment by tom-andersson** [comment]
https://github.com/tom-andersson/deepsensor/pull/36/commits/ae86a4c395b79602bfa9a6b3b8cbffaf0653e1d9 replaces the mean across time of the 5th percentile of distances with the 5th percentile of distances across time and space. In plain language, the method here infers the resolution of pandas data to be the distance between the closest 5% of neighbouring observations. 

The new algorithm is here - @jonas-scholz123 does this seem like a good approach? https://github.com/tom-andersson/deepsensor/blob/ae86a4c395b79602bfa9a6b3b8cbffaf0653e1d9/deepsensor/data/utils.py#L76-L117

**Comment by jonas-scholz123** [comment]
This seems sensible to me. For applications with fixed coordinates across time (e.g. fixed weather station locations) it would be more efficient to get a list of unique coordinates (across all times) and computing the pairwise distances on those unique coordinates. For my temperature downscaling experiments, that is what I did.

Your algorithm has the benefit of working even if you've got coordinates that significantly change across time.

**Comment by tom-andersson** [comment]
Hi @RohitRathore1, I've just cherry-picked our combined commits into `main` (without the extraneous files), and I'll close this PR now. Your contribution is appreciated.

Note, since `deepsensor` is in an early stage and undergoing rapid development, I would recommend discussing a PR with an active maintainer before opening one in future. In this case, the issue being addressed was complicated and I could have recommended a simpler issue!

**Comment by RohitRathore1** [comment]
Hey @tom-andersson ,

Thank you for your review and feedback on the PR. It's always valuable to get insights from experienced members of the community. I completely understand the rapid development stage of `deepsensor` and the need for coordination before making PRs. I'll make sure to liaise with active maintainers beforehand in the future to ensure smoother collaboration. You are the active maintainer, right? And is there any other communication channel?

Thanks again for your time and guidance.

Best regards,
Rohit

**Pull request closed without merging**
